version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`welldev.tk`, `todo.welldev.com.br`,  `www.todo.welldev.com.br`)"
      - "traefik.http.routers.app.entrypoints=web"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`welldev.com.br`)"
      - "traefik.http.routers.whoami.entrypoints=web"
 